spring:
  datasource:
    url: jdbc:mysql://kitten-paws.mysql.database.azure.com:3306/kitten_paws_db?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: shopkeeper@kitten-paws
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 829915623535-diingeebnekg66sba4n0b7e4efofm8p4.apps.googleusercontent.com
            clientSecret:
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 355932348368504
            clientSecret:
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret:
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)


app:
  auth:
    tokenSecret: 9
    tokenExpirationMsec: 36000000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
server:
  port: 8080
